services:
  zookeeper:
    image: zookeeper:3.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    volumes:
      - ./init.cql:/docker-entrypoint-initdb.d/init.cql   # Mount init.cql to auto-run at startup
    networks:
      - backend

  dataloader:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cassandra  # Ensure Cassandra is running before loading data
    volumes:
      - ./data:/data  # Mount the data folder to the container
    environment:
      - CASSANDRA_HOST=cassandra  # Use 'cassandra' as the hostname
    entrypoint: ["python", "/dataloader.py"]  # Run dataloader.py when the container starts
    networks:
      - backend

networks:
  backend:
    driver: bridge
