from cassandra.cluster import Cluster
from cassandra.query import BatchStatement
from cassandra.auth import PlainTextAuthProvider
import json
import csv

# This secure connect bundle is autogenerated when you download your SCB, 
# if yours is different update the file name below
cloud_config= {
  'secure_connect_bundle': './secret/secure-connect-moocassandra.zip'
}

# This token JSON file is autogenerated when you download your token, 
# if yours is different update the file name below
with open("./secret/MOOCASSANDRA-token.json") as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()
session.set_keyspace('BIG_MOOC')

def delete_not_trained_courses():
    delete_stmt = session.prepare("DELETE FROM courses WHERE course_id = ?")
    rows = session.execute("SELECT course_id FROM courses WHERE is_trained = false ALLOW FILTERING")
    for row in rows:
        session.execute(delete_stmt, (row.course_id,))

delete_not_trained_courses()
