version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=Robert  # Set the cluster name
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
    ports:
      - "9042:9042"  # Expose port 9042 for Cassandra access
    volumes:
      - ./binded_mount:/var/lib/cassandra
      - ./init.cql:/docker-entrypoint-initdb.d/init.cql
    networks:
      - cassandra_net

  app:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile  # Specify your Dockerfile (optional if named Dockerfile)
    image: ippapi/big_mooc_nodes:latest  # Tag the image as 'myapp:latest'
    container_name: data_loader_app
    depends_on:
      - cassandra  # Ensure Cassandra starts before the app
    environment:
      - CASSANDRA_HOST=cassandra  # Use the service name as the host
      - CASSANDRA_PORT=9042
    volumes:
      - .:/app
    networks:
      - cassandra_net

networks:
  cassandra_net:
    driver: bridge

volumes:
  cassandra_data:
