from cassandra.cluster import Cluster
from cassandra.query import BatchStatement
from cassandra.auth import PlainTextAuthProvider
import json
import csv

# This secure connect bundle is autogenerated when you download your SCB, 
# if yours is different update the file name below
cloud_config= {
  'secure_connect_bundle': './secret/secure-connect-moocassandra.zip'
}

# This token JSON file is autogenerated when you download your token, 
# if yours is different update the file name below
with open("./secret/MOOCASSANDRA-token.json") as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()
session.set_keyspace('BIG_MOOC')

def update_courses():
    batch_size = 50
    batch = BatchStatement()
    count = 0

    with open('./data/course.csv') as f:
        reader = csv.DictReader(f)
        for row in reader:
            batch.add("""
                UPDATE courses SET is_trained = false WHERE course_id = (%s)
            """, (row["id"],))

            count += 1

            if count % batch_size == 0:
                session.execute(batch)
                batch = BatchStatement()

    if len(batch) > 0:
        session.execute(batch)

def update_trained_courses():
    batch_size = 50
    batch = BatchStatement()
    count = 0

    with open('./data/course_map.csv') as f:
        reader = csv.DictReader(f)
        for row in reader:
            batch.add("""
                UPDATE courses SET is_trained = true WHERE course_id = (%s)
            """, (row["course_id"],))

            count += 1

            if count % batch_size == 0:
                session.execute(batch)
                batch = BatchStatement()

    if len(batch) > 0:
        session.execute(batch)

update_courses()
update_trained_courses()
